ALTER TABLE `items` 
ADD COLUMN `pack_small_qty` INT(11) NOT NULL DEFAULT 0,
ADD COLUMN `pack_medium_qty` INT(11) NOT NULL DEFAULT 0,
ADD COLUMN `pack_biggest_qty` INT(11) NOT NULL DEFAULT 0,
ADD COLUMN `pack_small_price` DECIMAL(10,2) NOT NULL DEFAULT 115.00,
ADD COLUMN `pack_medium_price` DECIMAL(10,2) NOT NULL DEFAULT 185.00,
ADD COLUMN `pack_biggest_price` DECIMAL(10,2) NOT NULL DEFAULT 335.00;
